### ISSUE TITLE
可否有训练功能

### ISSUE THREAD

**Issue by dmarkdmark** [junyangfan/ai-image-qa#1]
我在社区看到该项目，发现很符合我目前的一个需求，但有缺点：
一个游戏，每天需要答题：一部分是游戏内容答题，所以我需要训练模型给我提供正确的游戏答案，一部分是全球生活百科（各种各样的题目，上知天文地理，下知生火造饭）

**Comment by jyfan-n** [comment]
> 我在社区看到该项目，发现很符合我目前的一个需求，但有缺点： 一个游戏，每天需要答题：一部分是游戏内容答题，所以我需要训练模型给我提供正确的游戏答案，一部分是全球生活百科（各种各样的题目，上知天文地理，下知生火造饭）

目前不支持本地模型，因为本地模型类型太多，而且不同的人接入方式不一样，后续如果可以的话，搞个接入本地模型的方式

**Comment by dmarkdmark** [comment]
> > 我在社区看到该项目，发现很符合我目前的一个需求，但有缺点： 一个游戏，每天需要答题：一部分是游戏内容答题，所以我需要训练模型给我提供正确的游戏答案，一部分是全球生活百科（各种各样的题目，上知天文地理，下知生火造饭）
> 
> 目前不支持本地模型，因为本地模型类型太多，而且不同的人接入方式不一样，后续如果可以的话，搞个接入本地模型的方式

感谢回答

**Comment by dmarkdmark** [comment]
> > 我在社区看到该项目，发现很符合我目前的一个需求，但有缺点： 一个游戏，每天需要答题：一部分是游戏内容答题，所以我需要训练模型给我提供正确的游戏答案，一部分是全球生活百科（各种各样的题目，上知天文地理，下知生火造饭）
> 
> 目前不支持本地模型，因为本地模型类型太多，而且不同的人接入方式不一样，后续如果可以的话，搞个接入本地模型的方式

感谢回答
